DROP TABLE "shareezy"."BENUTZER" ;
insert into "shareezy"."BENUTZER" (ID, KURZNAME, EMAIL, KENNWORT, VORNAME, NACHNAME, hash) values(1,'musterbenutzer','muster@gmail.com','muster123', 'Max', 'Musterman', 'ja was soll hier bitte rein?');

CREATE TABLE "shareezy"."TYPEN" (
       "ID" INTEGER NOT NULL
     , "NAME" VARCHAR(128)
);
insert into "shareezy"."TYPEN" values (1,'Test typ Ressource');


CREATE TABLE "shareezy"."RESSOURCEN" (
       "ID" INTEGER NOT NULL
     , "NAME" VARCHAR(128) NOT NULL
     , "BESCHREIBUNG" CLOB(10 K)
     , "BILD" BLOB(1 M)
     , "EINSTELLUNGSDATUM" DATE NOT NULL
     , "ENDDATUM" DATE NOT NULL
     , "STARTDATUM" DATE NOT NULL
     , "BENUTZER_ID_EIGENTÜMER" INTEGER NOT NULL
     , "TYPEN_ID" INTEGER NOT NULL
);
INSERT into "shareezy"."RESSOURCEN" (ID, NAME, BESCHREIBUNG, EINSTELLUNGSDATUM, ENDDATUM, STARTDATUM, BENUTZER_ID_EIGENTÜMER, TYPEN_ID) values(
		1
	,	'TestRessource'
	,	'Ein CLOB ist also nur ein Text, der sehr lang ist und nur auf einen Speicherplatz und nicht auf eine Anzahl von Zeichen beschränkt ist.'
	,	'2013-05-03'
	,	'2013-05-03'
	,	'2013-12-04'
	,	1
	,	1
);

CREATE TABLE "shareezy"."GRUPPEN" (
       "ID" INTEGER NOT NULL
     , "NAME" VARCHAR(128) NOT NULL
     , "KENNWORT" VARCHAR(128) NOT NULL
     , "BENUTZER_ID_VERWALTER" INTEGER NOT NULL
);

CREATE TABLE "shareezy"."VERFÜGBARKEITEN" (
       "RESSORCEN_ID" INTEGER NOT NULL
     , "GRUPPEN_ID" INTEGER NOT NULL
);

CREATE TABLE "shareezy"."BENUTZERGRUPPEN" (
       "BENUTZER_ID" INTEGER NOT NULL
     , "GRUPPEN_ID" INTEGER NOT NULL
     , "bestätigt" INTEGER NOT NULL
);

CREATE TABLE "shareezy"."BUCHUNGEN" (
       "AUSLEIHDATUM" DATE NOT NULL
     , "RÜCKGABEDATUM" DATE NOT NULL
     , "BENUTZER_ID_AUSLEIHER" INTEGER NOT NULL
     , "RESSOURCEN_ID" INTEGER NOT NULL
);

ALTER TABLE "shareezy"."BENUTZER"
  ADD CONSTRAINT "PK_BENUTZER"
      PRIMARY KEY ("ID");

ALTER TABLE "shareezy"."TYPEN"
  ADD CONSTRAINT "PK_TYPEN"
      PRIMARY KEY ("ID");

ALTER TABLE "shareezy"."RESSOURCEN"
  ADD CONSTRAINT "PK_RESSOURCEN"
      PRIMARY KEY ("ID");

ALTER TABLE "shareezy"."GRUPPEN"
  ADD CONSTRAINT "PK_GRUPPEN"
      PRIMARY KEY ("ID");

ALTER TABLE "shareezy"."VERFÜGBARKEITEN"
  ADD CONSTRAINT "PK_VERFÜGBARKEITEN"
      PRIMARY KEY ("RESSORCEN_ID", "GRUPPEN_ID");

ALTER TABLE "shareezy"."BENUTZERGRUPPEN"
  ADD CONSTRAINT "PK_BENUTZERGRUPPEN"
      PRIMARY KEY ("BENUTZER_ID", "GRUPPEN_ID");

ALTER TABLE "shareezy"."BUCHUNGEN"
  ADD CONSTRAINT "PK_BUCHUNGEN"
      PRIMARY KEY ("AUSLEIHDATUM", "BENUTZER_ID_AUSLEIHER", "RESSOURCEN_ID");

ALTER TABLE "shareezy"."RESSOURCEN"
  ADD CONSTRAINT "FK_Ressourcen_Typen"
      FOREIGN KEY ("TYPEN_ID")
      REFERENCES "shareezy"."TYPEN" ("ID");

ALTER TABLE "shareezy"."RESSOURCEN"
  ADD CONSTRAINT "FK_RESSOURCEN_BENUTZER"
      FOREIGN KEY ("BENUTZER_ID_EIGENTÜMER")
      REFERENCES "shareezy"."BENUTZER" ("ID");

ALTER TABLE "shareezy"."GRUPPEN"
  ADD CONSTRAINT "FK_GRUPPEN_BENUTZER"
      FOREIGN KEY ("BENUTZER_ID_VERWALTER")
      REFERENCES "shareezy"."BENUTZER" ("ID");

ALTER TABLE "shareezy"."VERFÜGBARKEITEN"
  ADD CONSTRAINT "FK_VERFÜGBARKEITEN_GRUPPEN"
      FOREIGN KEY ("GRUPPEN_ID")
      REFERENCES "shareezy"."GRUPPEN" ("ID");

ALTER TABLE "shareezy"."VERFÜGBARKEITEN"
  ADD CONSTRAINT "FK_VERFÜGBARKEITEN_RESSOURCEN"
      FOREIGN KEY ("RESSORCEN_ID")
      REFERENCES "shareezy"."RESSOURCEN" ("ID");

ALTER TABLE "shareezy"."BENUTZERGRUPPEN"
  ADD CONSTRAINT "FK_BENUTZERGRUPPEN_BENUTZER"
      FOREIGN KEY ("BENUTZER_ID")
      REFERENCES "shareezy"."BENUTZER" ("ID");

ALTER TABLE "shareezy"."BENUTZERGRUPPEN"
  ADD CONSTRAINT "FK_BENUTZERGRUPPEN_GRUPPEN"
      FOREIGN KEY ("GRUPPEN_ID")
      REFERENCES "shareezy"."GRUPPEN" ("ID");

ALTER TABLE "shareezy"."BUCHUNGEN"
  ADD CONSTRAINT "FK_BUCHUNGEN_RESSOURCEN"
      FOREIGN KEY ("RESSOURCEN_ID")
      REFERENCES "shareezy"."RESSOURCEN" ("ID");

ALTER TABLE "shareezy"."BUCHUNGEN"
  ADD CONSTRAINT "FK_BUCHUNGEN_BENUTZER"
      FOREIGN KEY ("BENUTZER_ID_AUSLEIHER")
      REFERENCES "shareezy"."BENUTZER" ("ID");

